### ISSUE TITLE
How should one define `public_code`?

### ISSUE THREAD

**Issue by albusdemens** [vh42720/csgo_cheater_detection#1]
Hello there, I'm trying to replicate your results and I'm now trying to download some users data. When I launch _00_collect_data.py_, I get the error `NameError: name 'public_code' is not defined` (see https://github.com/vh42720/csgo_cheater_detection/blob/d65bacf7350a177ab07018ad245979ee13f3479c/00_collect_data.py#L38). Should I hardcode `public_code` or is it something that is gathered from the downloaded data?

**Comment by vh42720** [comment]
Hi Alberto,

The public code is the code that identifies the account is public and is
available for gathering data. In this case, it is 3 (integer). I checked
the API notes and it is still the same so just hardcode it to 3 if you want.

public_code = 3

Best,
Vinh Hang

**Comment by albusdemens** [comment]
Thanks for your quick reply Vinh! And thanks for sharing your work.
